
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/product
    password:
  application:
    name: micro-comments
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 9080